.TH   _printf() "2021-17-03" "_printf() man page"
.SH NAME
_printf().
.SH SYNOPSIS
.B _printf()
.RB {| OBJECT |}
.RB [| OPTIONS |]
.SH DESCRIPTION
_printf() Print ARGUMENTS acordig to 
.B FORMAT
OR execute accordign to 
.B OPTIONS

.SH OPTIONS
.RS
.nf
	- c print a single character
	- s print a string of characters
	- % start a format specifications
	- d print a decimal
	- i print a integer
.RE
.SH AUTHOR
.I Carlos Galeano & Alexander Rodriguez Pineda
